# Generated by Django 4.1.2 on 2023-02-13 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='色(16進数)')),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mylife.category', verbose_name='カテゴリ'),
        ),
        migrations.DeleteModel(
            name='SCategory',
        ),
    ]
