# Generated by Django 4.1.2 on 2023-03-24 12:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0002_category_alter_schedule_category_delete_scategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='公開可能か'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(default=datetime.time(1, 0), verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='開始時間'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('schedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mylife.schedule')),
                ('title', models.CharField(max_length=40, verbose_name='タイトル')),
                ('persons', models.CharField(max_length=100, verbose_name='誰と')),
                ('place', models.CharField(max_length=50, verbose_name='場所')),
                ('relation_records', models.ManyToManyField(blank=True, to='mylife.record', verbose_name='関連記録')),
            ],
            bases=('mylife.schedule',),
        ),
    ]
