# Generated by Django 4.1.2 on 2023-04-05 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0003_schedule_is_public_alter_schedule_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='開始時間'),
        ),
    ]
