# Generated by Django 5.2.1 on 2025-09-03 18:11

import django.db.models.deletion
import django.utils.timezone
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
                ('color', models.CharField(default='#75715e', max_length=7, verbose_name='色(16進数)')),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='タイトル')),
                ('old_thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='旧サムネイル')),
                ('lead_text', models.TextField(verbose_name='紹介文')),
                ('main_text', markdownx.models.MarkdownxField(help_text='Markdown形式で記入', verbose_name='本文')),
                ('is_public', models.BooleanField(default=True, verbose_name='公開可能か')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myblog.category', verbose_name='カテゴリ')),
                ('relation_posts', models.ManyToManyField(blank=True, to='myblog.post', verbose_name='関連記事')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myblog.thumbnail', verbose_name='サムネイル')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
