# Generated by Django 5.2.1 on 2025-09-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composite',
            name='src',
            field=models.FileField(blank=True, null=True, upload_to='uploader/', verbose_name='ファイルソース'),
        ),
    ]
